// frontend/src/app/features/dashboard/settings/settings.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { LucideAngularModule } from 'lucide-angular';
import { toast } from 'ngx-sonner';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, LucideAngularModule],
  template: `
    <div class="max-w-4xl mx-auto space-y-8 p-6 md:p-10">
      <div>
        <h1 class="text-3xl font-bold text-slate-900">Configuración</h1>
        <p class="text-slate-600">Gestiona la información de la institución y preferencias.</p>
      </div>

      <div class="grid gap-8">

        <!-- Tarjeta: Información General -->
        <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div class="p-6 border-b border-slate-100 bg-slate-50/50">
            <h2 class="text-lg font-bold text-slate-900 flex items-center gap-2">
              <div class="p-2 bg-blue-100 rounded-lg text-blue-600">
                <lucide-icon name="building-2" class="w-5 h-5"></lucide-icon>
              </div>
              Información Institucional
            </h2>
          </div>

          <form [formGroup]="generalForm" (ngSubmit)="saveGeneral()" class="p-6 space-y-6">
            <div class="grid md:grid-cols-2 gap-6">
              <div class="space-y-1.5">
                <label class="text-sm font-semibold text-slate-700">Nombre de la Institución</label>
                <div class="relative">
                  <lucide-icon name="type" class="absolute left-3 top-2.5 w-4 h-4 text-slate-400"></lucide-icon>
                  <input formControlName="institutionName" class="pl-10 flex h-10 w-full rounded-lg border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 transition-all" />
                </div>
              </div>
              <div class="space-y-1.5">
                <label class="text-sm font-semibold text-slate-700">Correo de Contacto</label>
                <div class="relative">
                  <lucide-icon name="mail" class="absolute left-3 top-2.5 w-4 h-4 text-slate-400"></lucide-icon>
                  <input formControlName="contactEmail" class="pl-10 flex h-10 w-full rounded-lg border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 transition-all" />
                </div>
              </div>
              <div class="space-y-1.5">
                <label class="text-sm font-semibold text-slate-700">Teléfono</label>
                <input formControlName="phone" class="flex h-10 w-full rounded-lg border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 transition-all" />
              </div>
              <div class="space-y-1.5">
                <label class="text-sm font-semibold text-slate-700">Sitio Web</label>
                <div class="relative">
                  <lucide-icon name="globe" class="absolute left-3 top-2.5 w-4 h-4 text-slate-400"></lucide-icon>
                  <input formControlName="website" class="pl-10 flex h-10 w-full rounded-lg border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 transition-all" />
                </div>
              </div>
            </div>

            <div class="space-y-1.5">
              <label class="text-sm font-semibold text-slate-700">Dirección</label>
              <div class="relative">
                <lucide-icon name="map-pin" class="absolute left-3 top-3 w-4 h-4 text-slate-400"></lucide-icon>
                <textarea formControlName="address" rows="3" class="pl-10 flex w-full rounded-lg border border-slate-200 p-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 resize-none transition-all"></textarea>
              </div>
            </div>

            <div class="flex justify-end pt-2">
              <button type="submit" [disabled]="generalForm.invalid" class="bg-blue-600 text-white px-6 py-2.5 rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors flex items-center gap-2 shadow-sm disabled:opacity-50">
                <lucide-icon name="save" class="w-4 h-4"></lucide-icon> Guardar Cambios
              </button>
            </div>
          </form>
        </div>

        <!-- Tarjeta: Seguridad -->
        <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div class="p-6 border-b border-slate-100 bg-slate-50/50">
            <h2 class="text-lg font-bold text-slate-900 flex items-center gap-2">
              <div class="p-2 bg-purple-100 rounded-lg text-purple-600">
                <lucide-icon name="shield" class="w-5 h-5"></lucide-icon>
              </div>
              Seguridad y Preferencias
            </h2>
          </div>

          <div class="p-6 space-y-6">
            <div class="flex items-center justify-between">
              <div class="space-y-0.5">
                <label class="text-sm font-semibold text-slate-900">Notificaciones por Correo</label>
                <p class="text-xs text-slate-500">Recibir alertas cuando se crea una nueva reserva.</p>
              </div>
              <!-- Toggle Switch UI -->
              <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" class="sr-only peer" checked>
                <div class="w-11 h-6 bg-slate-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
              </label>
            </div>

            <hr class="border-slate-100">

            <div class="flex items-center justify-between">
              <div class="space-y-0.5">
                <label class="text-sm font-semibold text-slate-900">Aprobación Automática</label>
                <p class="text-xs text-slate-500">Las reservas se confirman automáticamente sin revisión manual.</p>
              </div>
              <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" class="sr-only peer">
                <div class="w-11 h-6 bg-slate-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
              </label>
            </div>
          </div>
        </div>

      </div>
    </div>
  `
})
export class SettingsComponent {
  private fb = inject(FormBuilder);

  generalForm = this.fb.group({
    institutionName: ['Universidad Nacional', Validators.required],
    contactEmail: ['admin@uni.edu.pe', [Validators.required, Validators.email]],
    phone: ['+51 987 654 321'],
    website: ['www.uni.edu.pe'],
    address: ['Av. Universitaria 1234, Lima, Perú']
  });

  saveGeneral() {
    if (this.generalForm.valid) {
      console.log(this.generalForm.value);
      toast.success('Configuración guardada exitosamente', {
        description: 'Los datos de la institución han sido actualizados.'
      });
    }
  }
}

// app/dashboard/settings/page.tsx
"use client"

import type React from "react"

import { Sidebar } from "@/components/sidebar"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Save, Lock, Bell, Shield } from "lucide-react"
import { useState } from "react"

export default function SettingsPage() {
  const [settings, setSettings] = useState({
    institutionName: "Universidad Nacional",
    email: "admin@universidad.com",
    phone: "+34 912 345 678",
    address: "Calle Principal 123, Madrid",
    notifications: true,
    emailAlerts: true,
    twoFactor: false,
  })

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target as HTMLInputElement
    setSettings((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? (e.target as HTMLInputElement).checked : value,
    }))
  }

  return (
    <div className="flex h-screen bg-slate-50">
      <Sidebar activeTab="settings" />

      <main className="flex-1 overflow-auto md:ml-0">
        <div className="p-4 md:p-8 max-w-4xl">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-slate-900">Configuración</h1>
            <p className="text-slate-600 mt-2">Gestiona la configuración de tu institución</p>
          </div>

          {/* General Settings */}
          <Card className="p-6 border border-slate-200 mb-6">
            <h2 className="text-xl font-bold text-slate-900 mb-6">Información general</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Nombre de la institución</label>
                <input
                  type="text"
                  name="institutionName"
                  value={settings.institutionName}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Correo electrónico</label>
                <input
                  type="email"
                  name="email"
                  value={settings.email}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Teléfono</label>
                <input
                  type="tel"
                  name="phone"
                  value={settings.phone}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Dirección</label>
                <textarea
                  name="address"
                  value={settings.address}
                  onChange={handleChange}
                  rows={3}
                  className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <Button className="bg-blue-600 hover:bg-blue-700">
                <Save className="w-4 h-4 mr-2" />
                Guardar cambios
              </Button>
            </div>
          </Card>

          {/* Notifications */}
          <Card className="p-6 border border-slate-200 mb-6">
            <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <Bell className="w-5 h-5" />
              Notificaciones
            </h2>
            <div className="space-y-4">
              <label className="flex items-center gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  name="notifications"
                  checked={settings.notifications}
                  onChange={handleChange}
                  className="w-4 h-4 rounded border-slate-300"
                />
                <span className="text-slate-700">Recibir notificaciones de nuevas reservas</span>
              </label>
              <label className="flex items-center gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  name="emailAlerts"
                  checked={settings.emailAlerts}
                  onChange={handleChange}
                  className="w-4 h-4 rounded border-slate-300"
                />
                <span className="text-slate-700">Recibir alertas por correo electrónico</span>
              </label>
            </div>
          </Card>

          {/* Security */}
          <Card className="p-6 border border-slate-200">
            <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <Shield className="w-5 h-5" />
              Seguridad
            </h2>
            <div className="space-y-4">
              <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
                <div className="flex items-center gap-3">
                  <Lock className="w-5 h-5 text-slate-600" />
                  <div>
                    <p className="font-medium text-slate-900">Autenticación de dos factores</p>
                    <p className="text-sm text-slate-600">Añade una capa extra de seguridad a tu cuenta</p>
                  </div>
                </div>
                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    name="twoFactor"
                    checked={settings.twoFactor}
                    onChange={handleChange}
                    className="w-4 h-4 rounded border-slate-300"
                  />
                </label>
              </div>
              <Button variant="outline" className="border-slate-300 bg-transparent">
                Cambiar contraseña
              </Button>
            </div>
          </Card>
        </div>
      </main>
    </div>
  )
}
