// components/space-modal.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { X } from "lucide-react"

interface SpaceModalProps {
  isOpen: boolean
  onClose: () => void
  onSave: (space: SpaceFormData) => void
  initialData?: SpaceFormData
  isEditing?: boolean
}

export interface SpaceFormData {
  id?: number
  name: string
  type: string
  capacity: number
  image: string
}

const spaceTypes = [
  { value: "sports", label: "Deporte" },
  { value: "study", label: "Estudio" },
  { value: "lab", label: "Laboratorio" },
  { value: "meeting", label: "Reunión" },
  { value: "library", label: "Biblioteca" },
]

const spaceEmojis = ["⚽", "📚", "🧪", "🏀", "🎤", "📖", "🎨", "🏋️", "🎭", "🖥️"]

export function SpaceModal({ isOpen, onClose, onSave, initialData, isEditing }: SpaceModalProps) {
  const [formData, setFormData] = useState<SpaceFormData>(
    initialData || {
      name: "",
      type: "sports",
      capacity: 20,
      image: "⚽",
    },
  )

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: name === "capacity" ? Number.parseInt(value) : value,
    }))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSave(formData)
    setFormData({
      name: "",
      type: "sports",
      capacity: 20,
      image: "⚽",
    })
  }

  if (!isOpen) return null

  return (
    <>
      {/* Overlay */}
      <div className="fixed inset-0 bg-black/50 z-40" onClick={onClose} />

      {/* Modal */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-md border border-slate-200 bg-white">
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-slate-200">
            <h2 className="text-xl font-bold text-slate-900">{isEditing ? "Editar espacio" : "Crear nuevo espacio"}</h2>
            <button onClick={onClose} className="p-1 hover:bg-slate-100 rounded-lg transition-colors">
              <X className="w-5 h-5 text-slate-600" />
            </button>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="p-6 space-y-4">
            {/* Name */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Nombre del espacio</label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="Ej: Cancha de fútbol A"
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>

            {/* Type */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Tipo de espacio</label>
              <select
                name="type"
                value={formData.type}
                onChange={handleChange}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                {spaceTypes.map((type) => (
                  <option key={type.value} value={type.value}>
                    {type.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Capacity */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Capacidad (personas)</label>
              <input
                type="number"
                name="capacity"
                value={formData.capacity}
                onChange={handleChange}
                min="1"
                max="500"
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>

            {/* Emoji Selection */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Icono del espacio</label>
              <div className="grid grid-cols-5 gap-2">
                {spaceEmojis.map((emoji) => (
                  <button
                    key={emoji}
                    type="button"
                    onClick={() => setFormData((prev) => ({ ...prev, image: emoji }))}
                    className={`p-3 text-2xl rounded-lg border-2 transition-colors ${
                      formData.image === emoji
                        ? "border-blue-500 bg-blue-50"
                        : "border-slate-200 hover:border-slate-300"
                    }`}
                  >
                    {emoji}
                  </button>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="flex-1 border-slate-300 bg-transparent"
              >
                Cancelar
              </Button>
              <Button type="submit" className="flex-1 bg-blue-600 hover:bg-blue-700">
                {isEditing ? "Actualizar" : "Crear"}
              </Button>
            </div>
          </form>
        </Card>
      </div>
    </>
  )
}

// frontend/src/app/features/dashboard/spaces/space-modal.component.ts
import { Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { SpacesService } from '../../../core/services/spaces.service';

@Component({
  selector: 'app-space-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div *ngIf="isOpen" class="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
      <div class="bg-white rounded shadow-lg w-full max-w-md p-6">
        <h3 class="text-lg font-semibold mb-2">{{ isEditing ? 'Editar Espacio' : 'Crear Espacio' }}</h3>

        <div *ngIf="error" class="mb-3 p-2 bg-red-100 text-red-700 rounded">{{ error }}</div>

        <form [formGroup]="form" (ngSubmit)="submit()">
          <div class="mb-3">
            <label class="block text-sm">Nombre</label>
            <input formControlName="name" class="w-full border px-2 py-1" />
          </div>
          <div class="mb-3">
            <label class="block text-sm">Tipo</label>
            <select formControlName="type" class="w-full border px-2 py-1">
              <option value="study">Sala de Estudio</option>
              <option value="lab">Laboratorio</option>
              <option value="sports">Cancha Deportiva</option>
              <option value="meeting">Sala de Reuniones</option>
              <option value="other">Otro</option>
            </select>
          </div>
          <div class="mb-3">
            <label class="block text-sm">Capacidad</label>
            <input type="number" formControlName="capacity" class="w-full border px-2 py-1" />
          </div>
          <div class="mb-4">
            <label class="block text-sm">Emoji/Imagen</label>
            <input formControlName="image" class="w-full border px-2 py-1" />
          </div>

          <div class="flex justify-end gap-2">
            <button type="button" class="px-3 py-1 border rounded" (click)="closeModal()" [disabled]="loading">Cancelar</button>
            <button type="submit" class="px-3 py-1 bg-blue-600 text-white rounded" [disabled]="loading">{{ loading ? 'Guardando...' : (isEditing ? 'Guardar' : 'Crear') }}</button>
          </div>
        </form>
      </div>
    </div>
  `,
  styles: []
})
export class SpaceModalComponent {
  @Input() isOpen = false;
  @Input() initialData: any = null;
  @Output() closed = new EventEmitter<void>();
  @Output() saved = new EventEmitter<void>();

  private fb = inject(FormBuilder);
  private spacesService = inject(SpacesService);

  form = this.fb.group({ name: [''], type: ['study'], capacity: [1], image: [''] });
  loading = false;
  error: string | null = null;

  get isEditing() { return !!this.initialData; }

  ngOnChanges() {
    if (this.initialData) {
      this.form.patchValue({
        name: this.initialData.name,
        type: this.initialData.type,
        capacity: this.initialData.capacity,
        image: this.initialData.image || ''
      });
      this.error = null;
    } else {
      this.form.reset({ name: '', type: 'study', capacity: 10, image: '' });
      this.error = null;
    }
  }

  submit() {
    if (this.form.invalid) return;
    this.loading = true;
    const payload = { ...this.form.value, image: this.form.value.image || null };

    const obs = this.isEditing ? this.spacesService.update(this.initialData.id, payload) : this.spacesService.create(payload);
    obs.subscribe({
      next: () => { this.loading = false; this.saved.emit(); },
      error: (err) => { this.loading = false; this.error = err?.error?.message || 'Error guardando espacio'; }
    });
  }

  closeModal() {
    if (!this.loading) this.closed.emit();
  }
}
