// components/dashboard/stat-card.tsx
import { Card } from "@/components/ui/card"
import type { LucideIcon } from "lucide-react"

interface StatCardProps {
  label: string
  value: string
  Icon: LucideIcon
  color: string
  change?: string
}

export function StatCard({ label, value, Icon, color, change }: StatCardProps) {
  return (
    <Card className="p-6 border border-slate-200">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-slate-600 text-sm font-medium">{label}</p>
          <p className="text-3xl font-bold text-slate-900 mt-2">{value}</p>
          {change && <p className="text-xs text-green-600 mt-2">{change}</p>}
        </div>
        <div className={`p-3 rounded-lg ${color}`}>
          <Icon className="w-6 h-6" />
        </div>
      </div>
    </Card>
  )
}

// frontend/src/app/features/dashboard/stat-card/stat-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-stat-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-white rounded-lg shadow p-4">
      <div class="flex items-center justify-between">
        <div>
          <div class="text-sm text-slate-500">{{ title }}</div>
          <div class="text-2xl font-semibold text-slate-900">{{ value }}</div>
        </div>
        <div *ngIf="icon" class="text-slate-400">{{ icon }}</div>
      </div>
    </div>
  `,
  styles: []
})
export class StatCardComponent {
  @Input() title = '';
  @Input() value: string | number = '';
  @Input() icon?: string;
}
